### ISSUE TITLE
Duplicating any Potion as long as you start with 1 of that kind

### ISSUE THREAD

**Issue by CzM105** [Zemelua/UMU-Arcanum#1]
Taking 1 Potion of any kind and 2 Water Bottles you are able to duplicate 1 Potion into 3 Potions, effectively meaning infinite potions of any kind as long as you have made 1 of that kind and have water bottles to use.

**Comment by Zemelua** [comment]
When you first pour a potion into the cauldron, the cauldron records the type of potion. Since the second and subsequent injections are recorded as an effect rather than a potion, the effect time will change depending on the content, but since the "potion" is the same as the effect and time, it will be the same at any time. In order to change the scooped item name to "potion of XXX", it is necessary to record the potion, but this certainly does not keep the game balance. I would like to make some changes in the future. Or I am waiting for a better improvement.
